/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc428_p2;

/**
 *
 * @author Ignacio
 */
public class JActionLog extends javax.swing.JInternalFrame {

    private JInternalPPT parent;
    private int order;
    private int slidesAdded;
    
    /**
     * Creates new form JActionLog
     */
    public JActionLog(JInternalPPT parent, int order, int slidesAdded) {
        initComponents();
        this.parent = parent;
        this.order = order;
        this.slidesAdded = slidesAdded;
        
        if (order == 1) {
            lblActionLog1.setText("Image inserted");
            lblActionLog2.setText("New slide (x" + slidesAdded + ")");
        } else {
            lblActionLog1.setText("New slide (x" + slidesAdded + ")");
            lblActionLog2.setText("Image inserted");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActionLogTitle = new javax.swing.JLabel();
        btnConfirmActions = new javax.swing.JButton();
        btnCancelActionLog = new javax.swing.JButton();
        lblActionLog2 = new javax.swing.JLabel();
        lblActionLog1 = new javax.swing.JLabel();

        lblActionLogTitle.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblActionLogTitle.setText("Actions identified:");

        btnConfirmActions.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnConfirmActions.setText("Confirm");
        btnConfirmActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionsActionPerformed(evt);
            }
        });

        btnCancelActionLog.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnCancelActionLog.setText("Cancel");
        btnCancelActionLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionLogActionPerformed(evt);
            }
        });

        lblActionLog2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblActionLog2.setText("action2");

        lblActionLog1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblActionLog1.setText("action1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(496, Short.MAX_VALUE)
                        .addComponent(btnCancelActionLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmActions))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblActionLogTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblActionLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActionLog2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActionLogTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblActionLog1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblActionLog2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmActions)
                    .addComponent(btnCancelActionLog))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionsActionPerformed
        JApplyRecording ar = new JApplyRecording(parent, order, slidesAdded);
        parent.showApplyAction(ar);
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionsActionPerformed

    private void btnCancelActionLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionLogActionPerformed
        parent.setContentsVisible();
        parent.resetRecordedActions();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionLogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelActionLog;
    private javax.swing.JButton btnConfirmActions;
    private javax.swing.JLabel lblActionLog1;
    private javax.swing.JLabel lblActionLog2;
    private javax.swing.JLabel lblActionLogTitle;
    // End of variables declaration//GEN-END:variables
}
