/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc428_p2;

/**
 *
 * @author Ignacio
 */
public class JApplyRecording extends javax.swing.JInternalFrame {

    private JInternalPPT parent;
    private int order;
    private int slidesAdded;
    private String[] selections;
    
    /**
     * Creates new form JApplyRecording
     * @param parent - the parent frame
     * @param order - determines whether the insertion or adding the slide came
     *      first; 1 if it was image insertion and 2 if it was adding the slide
     * @param slidesAdded - the number of frames added
     * 
     */
    public JApplyRecording(JInternalPPT parent, int order, int slidesAdded) {
        this.parent = parent;
        this.order = order;
        this.slidesAdded = slidesAdded;
        selections = new String[3];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfirmImages = new javax.swing.JLabel();
        lblApplyCat = new javax.swing.JLabel();
        lblApplyDog = new javax.swing.JLabel();
        lblApplyBird = new javax.swing.JLabel();
        chkbxApplyCat = new javax.swing.JCheckBox();
        chkbxApplyDog = new javax.swing.JCheckBox();
        chkbxApplyBird = new javax.swing.JCheckBox();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setResizable(true);

        lblConfirmImages.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblConfirmImages.setText("Select images to apply recording:");

        lblApplyCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/cat_thumbnail.png"))); // NOI18N

        lblApplyDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/dog_thumbnail.png"))); // NOI18N

        lblApplyBird.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/bird_thumbnail.png"))); // NOI18N

        chkbxApplyCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxApplyCatActionPerformed(evt);
            }
        });

        chkbxApplyDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxApplyDogActionPerformed(evt);
            }
        });

        chkbxApplyBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxApplyBirdActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblApplyCat)
                                .addGap(35, 35, 35)
                                .addComponent(lblApplyDog)
                                .addGap(34, 34, 34)
                                .addComponent(lblApplyBird))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(chkbxApplyCat)
                                    .addGap(114, 114, 114)
                                    .addComponent(chkbxApplyDog)
                                    .addGap(109, 109, 109)
                                    .addComponent(chkbxApplyBird))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(lblConfirmImages))))
                        .addGap(0, 344, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApply)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfirmImages)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApplyCat)
                    .addComponent(lblApplyDog)
                    .addComponent(lblApplyBird))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkbxApplyCat)
                    .addComponent(chkbxApplyDog)
                    .addComponent(chkbxApplyBird))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        parent.setContentsVisible();
        parent.resetRecordedActions();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        parent.applyRecordedActions(selections, order, slidesAdded);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnApplyActionPerformed

    private void chkbxApplyCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxApplyCatActionPerformed
        if (chkbxApplyCat.isSelected()) {
            int i = 0;
            while (i < 3) {
                if (selections[i] == null || selections[i].equals("")) {
                    selections[i] = "cat";
                    return;
                }
                i++;
            }
        } else {
            if (selections[0].equals("cat")) {
                selections[0] = selections[1];
                selections[1] = selections[2];
            } else if (selections[1].equals("cat")) {
                selections[1] = selections[2];
            }
            selections[2] = "";
        }
    }//GEN-LAST:event_chkbxApplyCatActionPerformed

    private void chkbxApplyDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxApplyDogActionPerformed
        if (chkbxApplyDog.isSelected()) {
            int i = 0;
            while (i < 3) {
                if (selections[i] == null || selections[i].equals("")) {
                    selections[i] = "dog";
                    return;
                }
                i++;
            }
        } else {
            if (selections[0].equals("dog")) {
                selections[0] = selections[1];
                selections[1] = selections[2];
            } else if (selections[1].equals("dog")) {
                selections[1] = selections[2];
            }
            selections[2] = "";
        }
    }//GEN-LAST:event_chkbxApplyDogActionPerformed

    private void chkbxApplyBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxApplyBirdActionPerformed
        if (chkbxApplyBird.isSelected()) {
            int i = 0;
            while (i < 3) {
                if (selections[i] == null || selections[i].equals("")) {
                    selections[i] = "bird";
                    return;
                }
                i++;
            }
        } else {
            if (selections[0].equals("bird")) {
                selections[0] = selections[1];
                selections[1] = selections[2];
            } else if (selections[1].equals("bird")) {
                selections[1] = selections[2];
            }
            selections[2] = "";
        }
    }//GEN-LAST:event_chkbxApplyBirdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JCheckBox chkbxApplyBird;
    private javax.swing.JCheckBox chkbxApplyCat;
    private javax.swing.JCheckBox chkbxApplyDog;
    private javax.swing.JLabel lblApplyBird;
    private javax.swing.JLabel lblApplyCat;
    private javax.swing.JLabel lblApplyDog;
    private javax.swing.JLabel lblConfirmImages;
    // End of variables declaration//GEN-END:variables
}
