/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc428_p2;

import java.awt.Color;

/**
 *
 * @author Ignacio
 */
public class JInsertingImage extends javax.swing.JInternalFrame {

    private JInternalPPT parent;
    private boolean catSelected;
    private boolean dogSelected;
    private boolean birdSelected;
    
    /**
     * Creates new form JInsertingImage
     */
    public JInsertingImage(JInternalPPT parent) {
        initComponents();
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpInsert = new javax.swing.ButtonGroup();
        pnlInsert = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlInsertCat = new javax.swing.JPanel();
        btnSelectCat = new javax.swing.JButton();
        lblCatTitle = new javax.swing.JLabel();
        pnlInsertDog = new javax.swing.JPanel();
        btnSelectDog = new javax.swing.JButton();
        lblDogTitle = new javax.swing.JLabel();
        pnlInsertBird = new javax.swing.JPanel();
        btnInsertBird = new javax.swing.JButton();
        lblBirdTitle = new javax.swing.JLabel();
        lblSidebar = new javax.swing.JLabel();

        pnlInsert.setBackground(new java.awt.Color(255, 255, 255));

        btnInsert.setText("Confirm");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pnlInsertCat.setBackground(new java.awt.Color(255, 255, 255));

        btnSelectCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/cat_thumbnail.png"))); // NOI18N
        btnSelectCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCatActionPerformed(evt);
            }
        });

        lblCatTitle.setText("cat.jpg");

        javax.swing.GroupLayout pnlInsertCatLayout = new javax.swing.GroupLayout(pnlInsertCat);
        pnlInsertCat.setLayout(pnlInsertCatLayout);
        pnlInsertCatLayout.setHorizontalGroup(
            pnlInsertCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertCatLayout.createSequentialGroup()
                .addGroup(pnlInsertCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsertCatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSelectCat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsertCatLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblCatTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInsertCatLayout.setVerticalGroup(
            pnlInsertCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelectCat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCatTitle)
                .addContainerGap())
        );

        pnlInsertDog.setBackground(new java.awt.Color(255, 255, 255));

        btnSelectDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/dog_thumbnail.png"))); // NOI18N
        btnSelectDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectDogActionPerformed(evt);
            }
        });

        lblDogTitle.setText("dog.jpg");

        javax.swing.GroupLayout pnlInsertDogLayout = new javax.swing.GroupLayout(pnlInsertDog);
        pnlInsertDog.setLayout(pnlInsertDogLayout);
        pnlInsertDogLayout.setHorizontalGroup(
            pnlInsertDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertDogLayout.createSequentialGroup()
                .addGroup(pnlInsertDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsertDogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSelectDog, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsertDogLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblDogTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInsertDogLayout.setVerticalGroup(
            pnlInsertDogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertDogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelectDog, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDogTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInsertBird.setBackground(new java.awt.Color(255, 255, 255));

        btnInsertBird.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/bird_thumbnail.png"))); // NOI18N
        btnInsertBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertBirdActionPerformed(evt);
            }
        });

        lblBirdTitle.setText("bird.jpg");

        javax.swing.GroupLayout pnlInsertBirdLayout = new javax.swing.GroupLayout(pnlInsertBird);
        pnlInsertBird.setLayout(pnlInsertBirdLayout);
        pnlInsertBirdLayout.setHorizontalGroup(
            pnlInsertBirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertBirdLayout.createSequentialGroup()
                .addGroup(pnlInsertBirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsertBirdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInsertBird, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInsertBirdLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblBirdTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInsertBirdLayout.setVerticalGroup(
            pnlInsertBirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertBirdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertBird, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBirdTitle)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlInsertLayout = new javax.swing.GroupLayout(pnlInsert);
        pnlInsert.setLayout(pnlInsertLayout);
        pnlInsertLayout.setHorizontalGroup(
            pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInsertLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInsert)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(29, 29, 29))
            .addGroup(pnlInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInsertCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInsertDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInsertBird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlInsertLayout.setVerticalGroup(
            pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInsertLayout.createSequentialGroup()
                        .addComponent(pnlInsertCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInsertLayout.createSequentialGroup()
                        .addGroup(pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlInsertDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlInsertBird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(243, 243, 243)))
                .addGroup(pnlInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnInsert))
                .addGap(27, 27, 27))
        );

        lblSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/InsertSidebar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSidebar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSidebar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if (catSelected) {
            parent.mapImageToSlide("cat");
        } else if (dogSelected) {
            parent.mapImageToSlide("dog");
        } else if (birdSelected) {
            parent.mapImageToSlide("bird");
        } 
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelectCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCatActionPerformed
        catSelected = !catSelected;
        if (catSelected) {
            pnlInsertCat.setBackground(Color.LIGHT_GRAY);
            dogSelected = false;
            pnlInsertDog.setBackground(Color.WHITE);
            birdSelected = false;
            pnlInsertBird.setBackground(Color.WHITE);
        } else {
            pnlInsertCat.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btnSelectCatActionPerformed

    private void btnSelectDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectDogActionPerformed
        dogSelected = !dogSelected;
        if (dogSelected) {
            pnlInsertDog.setBackground(Color.LIGHT_GRAY);
            catSelected = false;
            pnlInsertCat.setBackground(Color.WHITE);
            birdSelected = false;
            pnlInsertBird.setBackground(Color.WHITE);
        } else {
            pnlInsertDog.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btnSelectDogActionPerformed

    private void btnInsertBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertBirdActionPerformed
        birdSelected = !birdSelected;
        if (birdSelected) {
            pnlInsertBird.setBackground(Color.LIGHT_GRAY);
            catSelected = false;
            pnlInsertCat.setBackground(Color.WHITE);
            dogSelected = false;
            pnlInsertDog.setBackground(Color.WHITE);
        } else {
            pnlInsertBird.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btnInsertBirdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsertBird;
    private javax.swing.JButton btnSelectCat;
    private javax.swing.JButton btnSelectDog;
    private javax.swing.ButtonGroup btngrpInsert;
    private javax.swing.JLabel lblBirdTitle;
    private javax.swing.JLabel lblCatTitle;
    private javax.swing.JLabel lblDogTitle;
    private javax.swing.JLabel lblSidebar;
    private javax.swing.JPanel pnlInsert;
    private javax.swing.JPanel pnlInsertBird;
    private javax.swing.JPanel pnlInsertCat;
    private javax.swing.JPanel pnlInsertDog;
    // End of variables declaration//GEN-END:variables
}
