/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc428_p2;

/**
 *
 * @author ting
 */
public class JInternalPPT extends javax.swing.JInternalFrame {

    private int slideCurrent;
    private int slideCount;
    
    /**
     * Creates new form pptFrame
     */
    public JInternalPPT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCurrentSlide = new javax.swing.JLabel();
        bNewSlide = new javax.swing.JButton();
        txtChangeSlide = new javax.swing.JTextField();
        bChangeSlide = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lCurrentSlide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lCurrentSlide.setText("Slide 1");

        bNewSlide.setText("New Slide");
        bNewSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewSlideActionPerformed(evt);
            }
        });

        bChangeSlide.setText("Change Slide");
        bChangeSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangeSlideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCurrentSlide)
                .addGap(18, 18, 18)
                .addComponent(bNewSlide)
                .addGap(18, 18, 18)
                .addComponent(txtChangeSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bChangeSlide)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCurrentSlide)
                    .addComponent(bNewSlide)
                    .addComponent(txtChangeSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bChangeSlide))
                .addContainerGap(397, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNewSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewSlideActionPerformed
        slideCount++;
        slideCurrent = slideCount;
        lCurrentSlide.setText("Slide " + slideCurrent);
    }//GEN-LAST:event_bNewSlideActionPerformed

    private void bChangeSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangeSlideActionPerformed
        int value = Integer.parseInt(txtChangeSlide.getText());
        if(value <= slideCount){
            slideCurrent = value;
            lCurrentSlide.setText("Slide " + slideCurrent);
        }
    }//GEN-LAST:event_bChangeSlideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChangeSlide;
    private javax.swing.JButton bNewSlide;
    private javax.swing.JLabel lCurrentSlide;
    private javax.swing.JTextField txtChangeSlide;
    // End of variables declaration//GEN-END:variables
}
