/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc428_p2;

/**
 *
 * @author ting
 */
public class JInternalPPT extends javax.swing.JInternalFrame {

    private int slideCurrent;
    private int slideCount;
    private String[] imageMapping;
    private boolean recording;
    private String[] recordedActions;
    private int recordingIndex;
    
    /**
     * Creates new form pptFrame
     */
    public JInternalPPT() {
        initComponents();
        imageMapping = new String[20];
        slideCount = 1;
        slideCurrent = 1;
        recording = false;
        recordedActions = new String[20];
        recordingIndex = 0;
    }
    
    public void resetRecordedActions() {
        int i = 0;
        while (i <= recordingIndex) {
            recordedActions[i] = "";
            i++;
        }
        recordingIndex = 0;
    }
    
    public void setContentsVisible(){
        pnlCanvas.setVisible(true);
        pnlPPT.setVisible(true);
        btnRecord.setVisible(true);
    }
    
    public void mapImageToSlide(String image){ 
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/" + image + ".png")));
        imageMapping[slideCurrent] = image;
        
        if (recording) {
            recordedActions[recordingIndex] = "I";
            recordingIndex++;
        }
    }
    
    public void applyRecordedActions(String[] selections, int order, int slidesAdded) {
        int i = 0;
        while (i < 3) {
            if (!(selections[i] == null || selections[i].equals(""))) {
                int j = 0;
                if (order == 1){
                    imageMapping[slideCount] = selections[i];
                    while (j < slidesAdded) {
                        slideCount++;
                        j++;
                    }
                } else if (order == 2){
                    while (j < slidesAdded) {
                        slideCount++;
                        j++;
                    }
                    imageMapping[slideCount] = selections[i];
                }
            }
            i++;
        }
        String image = imageMapping[slideCurrent];
        if(!(image == null || image.equals(""))){
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/" + image + ".png")));
        } else {
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/blank.png")));
        }
        resetRecordedActions();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        pnlMain = new javax.swing.JPanel();
        pnlPPT = new javax.swing.JPanel();
        lblCurrentSlide = new javax.swing.JLabel();
        btnNewSlide = new javax.swing.JButton();
        btnChangeSlide = new javax.swing.JButton();
        pnlCanvas = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnInsertImage = new javax.swing.JButton();
        btnNavRight = new javax.swing.JButton();
        btnNavLeft = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblCurrentSlide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCurrentSlide.setText("Slide 1");

        btnNewSlide.setText("New Slide");
        btnNewSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSlideActionPerformed(evt);
            }
        });

        btnChangeSlide.setText("Change Slide");
        btnChangeSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSlideActionPerformed(evt);
            }
        });

        pnlCanvas.setBackground(new java.awt.Color(255, 255, 255));
        pnlCanvas.setMaximumSize(new java.awt.Dimension(504, 321));

        javax.swing.GroupLayout pnlCanvasLayout = new javax.swing.GroupLayout(pnlCanvas);
        pnlCanvas.setLayout(pnlCanvasLayout);
        pnlCanvasLayout.setHorizontalGroup(
            pnlCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCanvasLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        pnlCanvasLayout.setVerticalGroup(
            pnlCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCanvasLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        btnInsertImage.setText("Insert Image");
        btnInsertImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertImageActionPerformed(evt);
            }
        });

        btnNavRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/right-arrow.png"))); // NOI18N
        btnNavRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavRightActionPerformed(evt);
            }
        });

        btnNavLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/left-arrow.png"))); // NOI18N
        btnNavLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPPTLayout = new javax.swing.GroupLayout(pnlPPT);
        pnlPPT.setLayout(pnlPPTLayout);
        pnlPPTLayout.setHorizontalGroup(
            pnlPPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPPTLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPPTLayout.createSequentialGroup()
                        .addComponent(lblCurrentSlide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNewSlide)
                        .addGap(29, 29, 29)
                        .addComponent(btnNavLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChangeSlide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNavRight, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertImage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPPTLayout.setVerticalGroup(
            pnlPPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPPTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPPTLayout.createSequentialGroup()
                        .addGroup(pnlPPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPPTLayout.createSequentialGroup()
                                .addGroup(pnlPPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCurrentSlide)
                                    .addComponent(btnNewSlide)
                                    .addComponent(btnChangeSlide))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnNavRight, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnNavLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(pnlPPTLayout.createSequentialGroup()
                        .addComponent(btnInsertImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnlCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlPPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlPPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnRecord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRecord.setText("R");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecord))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRecord))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSlideActionPerformed
        if (slideCount < 20) {
            slideCount++;
            slideCurrent = slideCount;
            lblCurrentSlide.setText("Slide " + slideCurrent);
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/blank.png")));
            
            if (recording) {
                recordedActions[recordingIndex] = "N";
                recordingIndex++;
            }
        }
    }//GEN-LAST:event_btnNewSlideActionPerformed

    private void btnChangeSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSlideActionPerformed
        JNavigation n = new JNavigation(this, slideCount);
        pnlMain.add(n);
        pnlCanvas.setVisible(false);
        pnlPPT.setVisible(false);
        btnRecord.setVisible(false);
        n.show();
    }//GEN-LAST:event_btnChangeSlideActionPerformed

    private void btnInsertImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertImageActionPerformed

        JInsertingImage ii = new JInsertingImage(this);
        pnlMain.add(ii);
        pnlCanvas.setVisible(false);
        pnlPPT.setVisible(false);
        btnRecord.setVisible(false);
        ii.show();
        
    }//GEN-LAST:event_btnInsertImageActionPerformed

    public void showApplyAction(JApplyRecording ar){
        pnlMain.add(ar);
        pnlCanvas.setVisible(false);
        pnlPPT.setVisible(false);
        btnRecord.setVisible(false);
        ar.show();
    }
    
    public void changeSlide(int value) {
        if(value <= slideCount && value > 0){
            slideCurrent = value;
            lblCurrentSlide.setText("Slide " + slideCurrent);
        }
        String image = imageMapping[slideCurrent];
        if(!(image == null || image.equals(""))){
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/" + image + ".png")));
        } else {
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/blank.png")));
        }
    }
    
    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        boolean insertedImage = false;
        boolean newSlide = false;
        int order = 0;
        int slidesAdded = 0;
        int i = 0;
        recording = !recording;
        if (!recording) {
            btnRecord.setText("R");
            while(!(recordedActions[i] == null || recordedActions[i].equals(""))){
                if (recordedActions[i].equals("N")){
                    newSlide = true;
                    slidesAdded++;
                    if (order == 0){
                        order = 2;
                    }
                } else if (recordedActions[i].equals("I")){
                    insertedImage = true;
                    if (order == 0){
                        order = 1;
                    }
                }
                i++;
            }
            
            if (newSlide && insertedImage) {
                JActionLog al = new JActionLog(this, order, slidesAdded);
                pnlMain.add(al);
                pnlCanvas.setVisible(false);
                pnlPPT.setVisible(false);
                btnRecord.setVisible(false);
                al.show();
            }
            
        } else {
            btnRecord.setText("■");
        }
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnNavRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavRightActionPerformed
        int value = slideCurrent + 1;
        if(value <= slideCount && value > 0){
            slideCurrent = value;
            lblCurrentSlide.setText("Slide " + slideCurrent);
        }
        String image = imageMapping[slideCurrent];
        if(!(image == null || image.equals(""))){
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/" + image + ".png")));
        } else {
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/blank.png")));
        }
    }//GEN-LAST:event_btnNavRightActionPerformed

    private void btnNavLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLeftActionPerformed
        int value = slideCurrent - 1;
        if(value <= slideCount && value > 0){
            slideCurrent = value;
            lblCurrentSlide.setText("Slide " + slideCurrent);
        }
        String image = imageMapping[slideCurrent];
        if(!(image == null || image.equals(""))){
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/" + image + ".png")));
        } else {
            lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/blank.png")));
        }
    }//GEN-LAST:event_btnNavLeftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeSlide;
    private javax.swing.JButton btnInsertImage;
    private javax.swing.JButton btnNavLeft;
    private javax.swing.JButton btnNavRight;
    private javax.swing.JButton btnNewSlide;
    private javax.swing.JButton btnRecord;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel lblCurrentSlide;
    private javax.swing.JLabel lblImage;
    private javax.swing.JPanel pnlCanvas;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPPT;
    // End of variables declaration//GEN-END:variables
}
