/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc428_p2;

import javax.swing.JButton;

/**
 *
 * @author Ignacio
 */
public class JNavigation extends javax.swing.JInternalFrame {

    private JInternalPPT parent;
    private JButton[] allButtons;
    
    /**
     * Creates new form JNavigation
     */
    public JNavigation(JInternalPPT parent, int slideCount) {
        initComponents();
        this.parent = parent;
        allButtons = new JButton[20];
        allButtons[0] = btnSlide1;
        allButtons[1] = btnSlide2;
        allButtons[2] = btnSlide3;
        allButtons[3] = btnSlide4;
        allButtons[4] = btnSlide5;
        allButtons[5] = btnSlide6;
        allButtons[6] = btnSlide7;
        allButtons[7] = btnSlide8;
        allButtons[8] = btnSlide9;
        allButtons[9] = btnSlide10;
        allButtons[10] = btnSlide11;
        allButtons[11] = btnSlide12;
        allButtons[12] = btnSlide13;
        allButtons[13] = btnSlide14;
        allButtons[14] = btnSlide15;
        allButtons[15] = btnSlide16;
        allButtons[16] = btnSlide17;
        allButtons[17] = btnSlide18;
        allButtons[18] = btnSlide19;
        allButtons[19] = btnSlide20;
        initialiseButtons(slideCount);
    }

    public void initialiseButtons(int slideCount) {
        while (slideCount <= 19) {
            allButtons[slideCount].setVisible(false);
            slideCount++;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSlide2 = new javax.swing.JButton();
        lblNavTitle = new javax.swing.JLabel();
        btnSlide3 = new javax.swing.JButton();
        btnSlide1 = new javax.swing.JButton();
        btnSlide5 = new javax.swing.JButton();
        btnSlide4 = new javax.swing.JButton();
        btnSlide6 = new javax.swing.JButton();
        btnSlide7 = new javax.swing.JButton();
        btnSlide8 = new javax.swing.JButton();
        btnSlide9 = new javax.swing.JButton();
        btnSlide10 = new javax.swing.JButton();
        btnSlide11 = new javax.swing.JButton();
        btnSlide12 = new javax.swing.JButton();
        btnSlide13 = new javax.swing.JButton();
        btnSlide14 = new javax.swing.JButton();
        btnSlide15 = new javax.swing.JButton();
        btnSlide16 = new javax.swing.JButton();
        btnSlide17 = new javax.swing.JButton();
        btnSlide18 = new javax.swing.JButton();
        btnSlide19 = new javax.swing.JButton();
        btnSlide20 = new javax.swing.JButton();

        btnSlide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/2.png"))); // NOI18N
        btnSlide2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide2ActionPerformed(evt);
            }
        });

        lblNavTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNavTitle.setText("Select the slide to navigate to:");

        btnSlide3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/3.png"))); // NOI18N
        btnSlide3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide3ActionPerformed(evt);
            }
        });

        btnSlide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/1.png"))); // NOI18N
        btnSlide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide1ActionPerformed(evt);
            }
        });

        btnSlide5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/5.png"))); // NOI18N
        btnSlide5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide5ActionPerformed(evt);
            }
        });

        btnSlide4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/4.png"))); // NOI18N
        btnSlide4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide4ActionPerformed(evt);
            }
        });

        btnSlide6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/6.png"))); // NOI18N
        btnSlide6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide6ActionPerformed(evt);
            }
        });

        btnSlide7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/7.png"))); // NOI18N
        btnSlide7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide7ActionPerformed(evt);
            }
        });

        btnSlide8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/8.png"))); // NOI18N
        btnSlide8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide8ActionPerformed(evt);
            }
        });

        btnSlide9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/9.png"))); // NOI18N
        btnSlide9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide9ActionPerformed(evt);
            }
        });

        btnSlide10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/10.png"))); // NOI18N
        btnSlide10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide10ActionPerformed(evt);
            }
        });

        btnSlide11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/11.png"))); // NOI18N
        btnSlide11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide11ActionPerformed(evt);
            }
        });

        btnSlide12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/12.png"))); // NOI18N
        btnSlide12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide12ActionPerformed(evt);
            }
        });

        btnSlide13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/13.png"))); // NOI18N
        btnSlide13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide13ActionPerformed(evt);
            }
        });

        btnSlide14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/14.png"))); // NOI18N
        btnSlide14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide14ActionPerformed(evt);
            }
        });

        btnSlide15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/15.png"))); // NOI18N
        btnSlide15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide15ActionPerformed(evt);
            }
        });

        btnSlide16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/16.png"))); // NOI18N
        btnSlide16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide16ActionPerformed(evt);
            }
        });

        btnSlide17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/17.png"))); // NOI18N
        btnSlide17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide17ActionPerformed(evt);
            }
        });

        btnSlide18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/18.png"))); // NOI18N
        btnSlide18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide18ActionPerformed(evt);
            }
        });

        btnSlide19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/19.png"))); // NOI18N
        btnSlide19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide19ActionPerformed(evt);
            }
        });

        btnSlide20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csc428_p2/image/20.png"))); // NOI18N
        btnSlide20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlide20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblNavTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSlide1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlide6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlide11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlide16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlide20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNavTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSlide1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSlide2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSlide6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSlide11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSlide16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlide20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSlide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide1ActionPerformed
        parent.changeSlide(1);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide1ActionPerformed

    private void btnSlide2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide2ActionPerformed
        parent.changeSlide(2);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide2ActionPerformed

    private void btnSlide3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide3ActionPerformed
        parent.changeSlide(3);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide3ActionPerformed

    private void btnSlide4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide4ActionPerformed
        parent.changeSlide(4);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide4ActionPerformed

    private void btnSlide5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide5ActionPerformed
        parent.changeSlide(5);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide5ActionPerformed

    private void btnSlide6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide6ActionPerformed
        parent.changeSlide(6);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide6ActionPerformed

    private void btnSlide7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide7ActionPerformed
        parent.changeSlide(7);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide7ActionPerformed

    private void btnSlide8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide8ActionPerformed
        parent.changeSlide(8);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide8ActionPerformed

    private void btnSlide9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide9ActionPerformed
        parent.changeSlide(9);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide9ActionPerformed

    private void btnSlide10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide10ActionPerformed
        parent.changeSlide(10);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide10ActionPerformed

    private void btnSlide11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide11ActionPerformed
        parent.changeSlide(11);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide11ActionPerformed

    private void btnSlide12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide12ActionPerformed
        parent.changeSlide(12);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide12ActionPerformed

    private void btnSlide13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide13ActionPerformed
        parent.changeSlide(13);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide13ActionPerformed

    private void btnSlide14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide14ActionPerformed
        parent.changeSlide(14);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide14ActionPerformed

    private void btnSlide15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide15ActionPerformed
        parent.changeSlide(15);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide15ActionPerformed

    private void btnSlide16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide16ActionPerformed
        parent.changeSlide(16);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide16ActionPerformed

    private void btnSlide17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide17ActionPerformed
        parent.changeSlide(17);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide17ActionPerformed

    private void btnSlide18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide18ActionPerformed
        parent.changeSlide(18);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide18ActionPerformed

    private void btnSlide19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide19ActionPerformed
        parent.changeSlide(19);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide19ActionPerformed

    private void btnSlide20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlide20ActionPerformed
        parent.changeSlide(20);
        parent.setContentsVisible();
        this.dispose();
    }//GEN-LAST:event_btnSlide20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSlide1;
    private javax.swing.JButton btnSlide10;
    private javax.swing.JButton btnSlide11;
    private javax.swing.JButton btnSlide12;
    private javax.swing.JButton btnSlide13;
    private javax.swing.JButton btnSlide14;
    private javax.swing.JButton btnSlide15;
    private javax.swing.JButton btnSlide16;
    private javax.swing.JButton btnSlide17;
    private javax.swing.JButton btnSlide18;
    private javax.swing.JButton btnSlide19;
    private javax.swing.JButton btnSlide2;
    private javax.swing.JButton btnSlide20;
    private javax.swing.JButton btnSlide3;
    private javax.swing.JButton btnSlide4;
    private javax.swing.JButton btnSlide5;
    private javax.swing.JButton btnSlide6;
    private javax.swing.JButton btnSlide7;
    private javax.swing.JButton btnSlide8;
    private javax.swing.JButton btnSlide9;
    private javax.swing.JLabel lblNavTitle;
    // End of variables declaration//GEN-END:variables
}
